export default {
  ECONTRACT_DASHBOARD: 'ECONTRACT_DASHBOARD',
  // Hop Dong
  CREATE_CONTRACT: 'CREATE_CONTRACT',
  UPDATE_CONTRACT: 'UPDATE_CONTRACT',
  COORDINATION_CONTRACT: 'COORDINATION_CONTRACT',
  LIST_CONTRACT: 'LIST_CONTRACT',
  SIGN_CONTRACT: 'SIGN_CONTRACT',
  LIST_CONTRACT_PROCESS: 'LIST_CONTRACT_PROCESS',
  LIST_CONTRACT_COORDINATION: 'LIST_CONTRACT_COORDINATION',
  // Luong Mau
  CREATE_FLOW: 'CREATE_FLOW',
  UPDATE_FLOW: 'UPDATE_FLOW',
  LIST_FLOWS: 'LIST_FLOWS',
  // So Hoa
  CREATE_CONTRACT_DIGITZATION: 'CREATE_CONTRACT_DIGITZATION',
  UPDATE_CONTRACT_DIGITZATION: 'UPDATE_CONTRACT_DIGITZATION',
  LIST_CONTRACT_DIGITZATION: 'LIST_CONTRACT_DIGITZATION',
  // Bao Cao
  REPORT: 'REPORT'
}
