export default {
  DASHBOARD: 'DASHBOARD',
  DASHBOARD_HOME: 'DASHBOARD_HOME',
  // Auth
  LOGIN: 'LOGIN',
  LOGIN_AGENT: 'LOGIN_AGENT',
  LOGOUT: 'LOGOUT',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  // Don vi
  GROUP: 'GROUP',
  GROUP_CREATE: 'GROUP_CREATE',
  GROUP_UPDATE: 'GROUP_UPDATE',
  // User
  USERS: 'USERS',
  USER_DETAIL: 'USER_DETAIL',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_INFO: 'USER_INFO',
  // Notifi
  NOTIFICATION: "NOTIFICATION"
}
