export default {
  CALENDAR_DASHBOARD: 'CALENDAR_DASHBOARD',
  // lich hop.
  CALENDAR_MANAGEMENT_MEETING: 'CALENDAR_MANAGEMENT_MEETING',
  // chi tiet
  CALENDAR_MEETING_DETAIL: 'CALENDAR_MEETING_DETAIL',

  CALENDAR_VIEW: 'CALENDAR_VIEW'
}
