
export default {
  DASHBOARD: 'TASK_DASHBOARD',
  // TOI TAO
  I_CREATE: 'I_CREATE',
  UPDATE_TASK: 'UPDATE_TASK',
  VIEW_TASKl: 'VIEW_TASK',
  I_ASSIGN: 'I_ASSIGN',
  I_PERFORM: 'I_PERFORM',
  I_RELATE: 'I_RELATE',
  I_FOLLOW: 'I_FOLLOW',
  ROOM_WORK: 'I_ROOM_WORK',
  TYPE_TASK: 'TYPE_TASK'
}
