export default {
  ESIGNATURE_DASHBOARD: 'ESIGNATURE_DASHBOARD',
  // Ky dien tu.
  DOCUMENT_LIST_CREATE: 'ESIGNATURE_DOCUMENT_LIST_CREATE',
  DOCUMENT_LIST_PROCESS: 'ESIGNATURE_DOCUMENT_LIST_PROCESS',
  DOCUMENT_LIST_PROCLAIM: 'ESIGNATURE_DOCUMENT_LIST_PROCLAIM',
  CREATE_DOCUMENT: 'ESIGNATURE_CREATE_DOCUMENT',
  DOCUMENT_DETAIL: 'ESIGNATURE_DOCUMNET_DETAIL',
  UPDATE_DOCUMENT: 'ESIGNATURE_UPDATE_DOCUMENT',
  COPY_DOCUMENT: 'ESIGNATURE_COPY_DOCUMENT',

  // Luong Mau
  CREATE_FLOW: 'ESIGNATURE_CREATE_FLOW',
  UPDATE_FLOW: 'ESIGNATURE_UPDATE_FLOW',
  LIST_FLOWS: 'ESIGNATURE_LIST_FLOWS'
}
