/* eslint-disable key-spacing */
export default {
  TICKET_DASHBOARD: "TICKET_DASHBOARD",
  // Category ticket
  CATEGORIES_TICKET: "CATEGORIES_TICKET",
  CREATE_CATEGORY_TICKET: "CREATE_CATEGORY_TICKET",
  UPDATE_CATEGORY_TICKET: "UPDATE_CATEGORY_TICKET",

  // tickets
  MY_PERFORM_TICKET: "MY_PERFORM_TICKET",
  MY_REQUEST_TICKET: "MY_REQUEST_TICKET",
  MY_FOLLOW_TICKET: "MY_FOLLOW_TICKET",
  MY_APPROVE_TICKET: "MY_APPROVE_TICKET",
  TASK_CENTER_TICKET: "TASK_CENTER_TICKET",
  DEPARTMENT_TICKET: "DEPARTMENT_TICKET",
  DETAIL_TICKET: "DETAIL_TICKET",
  REPORT: "REPORT_TICKET"
};
